# Generated by Django 4.1.5 on 2023-01-07 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=15, verbose_name='Recipient Whatsapp number')),
                ('message', models.TextField(verbose_name='Text message to send')),
                ('pending', models.BooleanField(default=False, verbose_name='Defines whether the message is pending delivery')),
                ('scheduled_date', models.DateTimeField(null=True, verbose_name='Message sending schedule date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message owner')),
            ],
        ),
    ]
